### ISSUE TITLE
jwt token 生成方式

### ISSUE THREAD

**Issue by qiaoqiao888** [micyo202/lion#10]
### Ⅰ. 问题
如果使用jwt方式来代替oauth2本身的acctoken,在调用revoke的时候，jwt这个token是持续有效的，只能等自己过期吗？
### Ⅱ. 详细描述
如果有异常，请追加堆栈信息：
```
仅需将堆栈信息粘贴到这里!
```

### Ⅴ. 环境信息

- lion版本:
- jdk版本:
- 操作系统：
- 其他:

**Comment by qiaoqiao888** [comment]
不使用jwt去注销token，是ok的。
如果使用jwt，调用revoke接口，token系统还是认识的，这个时候这个登出如何来做嘞。
很多是redis+jwt，不知道大佬这边有方式吗

**Comment by micyo202** [comment]
JWT 的特点是无状态的，若用JWT来实现用户注销，有点违背了 JWT 的初衷

不过这种场景也可以将每一个签发的 JWT 保存在 Redis 上，当出现上述的需求时，就更新对应的JWT，每次登录进行客户端与 Redis 中 JWT 的比对，若不同，那么登录失败，这种方法虽然可以解决问题，但是此时 JWT 似乎又变成了有状态的了，失去了JWT的优点，采用 access_token 的方式它不香吗？

**Comment by qiaoqiao888** [comment]
说的也是，目前jwt也没有其他的好办法处理了。
