### ISSUE TITLE
微服务模块发布的RESTful接口，应该从哪里开始访问？

### ISSUE THREAD

**Issue by huaxuehuaxue** [micyo202/lion#13]
### Ⅰ. 问题
后台微服务模块发布了一个RESTful接口，一般都是直接接收数据请求的。应该从Web请求过来，还是直接将数据发送给Gateway？
### Ⅱ. 详细描述
如果有异常，请追加堆栈信息：
```
仅需将堆栈信息粘贴到这里!
```

### Ⅴ. 环境信息

- lion版本:
- jdk版本:
- 操作系统：
- 其他:

**Comment by micyo202** [comment]
既然采用微服务架构模式，当然所有的接口都要从 网关 模块发起，这样既保证了服务的统一入口，同时可以在 网关 模块进行统一的路由、限流、负载、规则过滤等相关操作。
具体交互细节可参考 [项目文档](https://github.com/micyo202/lion/blob/master/README.adoc) 中的 **项目架构图**
![项目架构图](https://camo.githubusercontent.com/31d66b7994958daa75be7ca41151a0fcf15fc6cc/68747470733a2f2f75706c6f61642d696d616765732e6a69616e7368752e696f2f75706c6f61645f696d616765732f383031353436312d633130323235653566313531643963302e706e673f696d6167654d6f6772322f6175746f2d6f7269656e742f73747269707c696d61676556696577322f322f772f31323030)
