### ISSUE TITLE
关于鉴权问题

### ISSUE THREAD

**Issue by ngcly** [micyo202/lion#3]
大佬，登录鉴权问题我有个疑问，我看了 你upms服务不需要登录就可以访问。正常来说在网关统一鉴权统一控制没什么问题， 但是单个服务不需要做限制么，如果单个服务接口被暴露出去岂不是都可以随便访问了，大佬能否提供个整体思路。

**Comment by micyo202** [comment]
设计是将upms部署在内网，auth服务部署在DMZ区，外网无法访问内网的upms，必须通过DMZ区的auth服务才能进行访问鉴权。

如果选择纯外网部署可将upms中的代码迁移至auth中，无需暴露对外接口，由auth服务中的UserDetailsServiceImpl直接调用即可

**Comment by ngcly** [comment]
明白了，感谢
