### ISSUE TITLE
gateway 发起授权码模式请求，走不通，可以看下这个问题吗

### ISSUE THREAD

**Issue by qiaoqiao888** [micyo202/lion#6]

**Comment by micyo202** [comment]
## 请按以下模板补充问题

### 1、问题描述

### 2、日志/堆栈信息
```
Just paste your stack trace here!
```

### 4、是否对工程进行修改，请说明修改内容

### 5、环境信息
- Lion Version: 
- Java Version:
- OS:
- Other:

**Comment by qiaoqiao888** [comment]
请按以下模板补充问题
1、问题描述
      启动网关，认证中心，然后进行授权码模式访问。访问过程中发现跳转到默认的登录页面后，登录成功，进入404，没有重定向至授权码的页面
2、日志/堆栈信息
Just paste your stack trace here!
4、是否对工程进行修改，请说明修改内容
5、环境信息
Lion Version: 最新版本
Java Version: 11
OS: 
Other:windows

**Comment by micyo202** [comment]
### 目前版本仅可采用密码模式（password），授权码模式（authorization_code）无法访问问题将在下个版本修复，该问题临时处理方式可参考以下步骤

- 1、修改[lion-common](https://github.com/micyo202/lion/tree/master/lion-common)下[com.lion.common.config.ResourceServerConfig.java](https://github.com/micyo202/lion/blob/master/lion-common/src/main/java/com/lion/common/config/ResourceServerConfig.java)内容
```java
@Configuration
@EnableResourceServer
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class ResourceServerConfig extends ResourceServerConfigurerAdapter {

    @Autowired
    private RedisConnectionFactory redisConnectionFactory;

    @Value("#{'${pattern.permit.urls:}'}")
    private String[] permitUrls;

    @Override
    public void configure(ResourceServerSecurityConfigurer resources) throws Exception {
        resources
                .tokenStore(new RedisTokenStore(redisConnectionFactory))
                .authenticationEntryPoint(new CustomAuthenticationEntryPoint())
                .accessDeniedHandler(new CustomAccessDeniedHandler());
    }

    @Override
    public void configure(HttpSecurity http) throws Exception {
        String[] excludeUrls = ArrayUtils.addAll(SecurityConstant.PATTERN_URLS, permitUrls);
        http
                .cors()
                .and()
                .csrf().disable()
                .requestMatchers().antMatchers("/api/**")
                .and()
                .authorizeRequests()
                .antMatchers(excludeUrls).permitAll()
                .anyRequest().authenticated();
    }
}
```
- 2、修改[lion-auth](https://github.com/micyo202/lion/tree/master/lion-auth)下[com.lion.auth.config.WebSecurityConfig.java](https://github.com/micyo202/lion/blob/master/lion-auth/src/main/java/com/lion/auth/config/WebSecurityConfig.java)内容
```java
@EnableWebSecurity
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

    @Autowired
    private UserDetailsServiceImpl userDetailsService;

    @Bean
    public PasswordEncoder passwordEncoder() {
        return PasswordEncoderFactories.createDelegatingPasswordEncoder();
    }

    @Bean
    @Override
    public AuthenticationManager authenticationManagerBean() throws Exception {
        return super.authenticationManagerBean();
    }

    @Override
    protected void configure(AuthenticationManagerBuilder auth) throws Exception {
        auth
                .userDetailsService(userDetailsService)
                .passwordEncoder(passwordEncoder());
    }

}
```

**Comment by qiaoqiao888** [comment]
从认证中心发起ok，授权码模式验证通过。
从网关发起之后，登录之后，404。我这边已经解决~
需要在路由中配置一下oauth的跳转，不知道大佬还有什么好的解决方案？
![image](https://user-images.githubusercontent.com/18333714/78450944-e405d600-76b4-11ea-8f17-d22dac736189.png)

**Comment by micyo202** [comment]
在路由中如何配置的oauth跳转？

**Comment by qiaoqiao888** [comment]
![image](https://user-images.githubusercontent.com/18333714/78649850-a2fa0580-78f0-11ea-89c8-b3ee56da2dda.png)
jingong
仅供参考~大佬可以尝试一下~

**Comment by micyo202** [comment]
无需配置多个路由规则，网关跳转404问题已经修复，下个版本会一起发布

**Comment by qiaoqiao888** [comment]
好的，大概啥时候发版本~

**Comment by micyo202** [comment]
**bugfix: since [2.0.3](https://github.com/micyo202/lion/releases/tag/2.0.3)**

**Comment by qiaoqiao888** [comment]
网关侧发起这个请求还是有问题~刚刚测试了下
![20200411_180930](https://user-images.githubusercontent.com/18333714/79041125-deae0b80-7c1f-11ea-9612-525788da7953.gif)

**Comment by qiaoqiao888** [comment]
网关发起还是有这个问题，最新代码测试~
认证中心ok~


![20200411_181252](https://user-images.githubusercontent.com/18333714/79041203-79a6e580-7c20-11ea-9ef0-7f36d27f5480.gif)

**Comment by sososdk** [comment]
@micyo202 授权码登录好像有些不对, 跳转到登录页面的地址是权限认证服务的地址, 应该跳转到网关地址才行吧.

**Comment by micyo202** [comment]
> @sososdk 

是指网关发起授权认证，跳转登录页面会重定向到auth服务的URL吗？
若想保证重定向依然在网关内地址，可采用 @qiaoqiao888 提供的配置多个路由规则方法：（https://github.com/micyo202/lion/issues/6#issuecomment-610265069）
将登录/授权重定向的url配置在gateway网关服务的路由规则里即可，在application.yml中增加配置如下，如下所示

```yml
        - id: lion-auth-login
          uri: lb://lion-auth
          predicates:
            - Path=/login
          filters:
            - PreserveHostHeader

        - id: lion-auth-authorize
          uri: lb://lion-auth
          predicates:
            - Path=/oauth/authorize
          filters:
            - PreserveHostHeader
```

**Comment by sososdk** [comment]
@micyo202 是的. 谢谢, 我去试试
