### ISSUE TITLE
详见 https://github.com/micyo202/lion/issues/6#issue-592669400

### ISSUE THREAD

**Issue by qiaoqiao888** [micyo202/lion#7]
https://github.com/micyo202/lion/issues/6#issuecomment-612385680

**Comment by micyo202** [comment]
错误的请求方式，不能使用localhost发起请求，需使用nacos中lion-gateway网关实例的ip地址进行请求
ip查看：进入nacos -> 服务管理 -> 服务列表 -> lion-gateway（服务详情）-> IP

<img width="1068" alt="WX20200411-201100@2x" src="https://user-images.githubusercontent.com/19185444/79043245-b4187e80-7c30-11ea-91fb-b231737f84c5.png">
