### ISSUE TITLE
使用方式请教

### ISSUE THREAD

**Issue by huaxuehuaxue** [micyo202/lion#9]
### Ⅰ. 问题
Gateway是直接到 provider 还是consumer 。

大神如果有时间，可否移步看一下这边文章：https://blog.csdn.net/cxz7456/article/details/105495578

### Ⅱ. 详细描述
        问题是：
                   应该怎么理解，是gateway直接访问到demo-provider  ？  还是gateway访问demo-consumer，然后demo-consumer再访问demo-provider ？

### Ⅴ. 环境信息

- lion版本:
- jdk版本:
- 操作系统：
- 其他:

**Comment by micyo202** [comment]
gateway 访问哪一层都是可以的，具体取决自身业务情况

当业务拆分粒度较粗或业务比较简单，这时候一个服务就可以完成，无需服务消费者，可以直接请求服务提供者，减少服务间调用的网络传输，性能也会比较好

当业务拆分粒度较细且需要较多服务调用的情况，需要从消费者->提供者这样模式一层一层自上而下的调用，这样减少了单一服务处理业务的复杂度，同时增加了整套系统的容错性，不会因为某一个服务宕掉，导致整套系统无法运行的情况，同样这样会增加服务http调用的网络开销

**Comment by huaxuehuaxue** [comment]
看了大佬的解释，省了看3天博客的时间。谢谢大佬。
